"""momasil

Revision ID: cf99a7a4a689
Revises: eed260a65806
Create Date: 2026-01-08 08:19:01.434958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf99a7a4a689'
down_revision: Union[str, Sequence[str], None] = 'eed260a65806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baskets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cafe_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('menu_id', sa.BigInteger(), nullable=False),
    sa.Column('basket_id', sa.BigInteger(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_basket_id'), 'items', ['basket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_basket_id'), table_name='items')
    op.drop_table('items')
    op.drop_table('baskets')
    # ### end Alembic commands ###
